---
# tasks file for zabbix_user_api

- name: Install zabbix-api on localhost
  pip:
    name: zabbix-api
    state: present
  delegate_to: localhost
  become: "{{ zabbix_user_api_become_on_localhost }}"

- name: Create custom Zabbix API user
  zabbix_user:
    server_url: "{{ zabbix_user_api_server_url }}"
    login_user: "{{ zabbix_user_api_default_Admin_user }}"
    login_password: "{{ zabbix_user_api_default_Admin_pass }}"
    alias: "{{ zabbix_user_api_api_user }}"
    name: "Zabbix"
    surname: "API"
    passwd: "{{ zabbix_user_api_api_pass }}"
    type: Zabbix super admin
    usrgrps:
          - "Zabbix administrators"
    state: present
  delegate_to: localhost
  become: "{{ zabbix_user_api_become_on_localhost }}"
  when:
    - zabbix_user_api_create_api_user | bool
    - zabbix_user_api_use_Admin_default_pass | bool

- name: Disable default Zabbix Admin user
  zabbix_user:
    server_url: "{{ zabbix_user_api_server_url }}"
    login_user: "{{ zabbix_user_api_api_user }}"
    login_password: "{{ zabbix_user_api_api_pass }}"
    alias: "{{ zabbix_user_api_default_Admin_user }}"
    passwd: "{{ zabbix_user_api_default_Admin_pass }}"
    type: Zabbix super admin
    usrgrps:
      - "Zabbix administrators"
      - "Disabled"
  delegate_to: localhost
  become: "{{ zabbix_user_api_become_on_localhost }}"
  when:
    - zabbix_user_api_disable_Admin_user | bool